### ISSUE TITLE
Dependency on Cartus.null

### ISSUE THREAD

**Issue by jordanrobinson** [logicblocks/salutem#2]
When adding `[io.logicblocks/salutem "0.1.0-RC11"]` to the project, I found that it also required a dependency of `[io.logicblocks/cartus.null "0.1.14"]` to be able to function.

Without it, I get the error:

```
Syntax error (FileNotFoundException) compiling at (salutem/checks.clj:1:1).
Could not locate cartus/null__init.class, cartus/null.clj or cartus/null.cljc on classpath.
```

**Comment by tobyclemson** [comment]
This is occurring because you should be adding `io.logicblocks/salutem.core`. Switch to that dependency and the issue should disappear.

**Comment by jordanrobinson** [comment]
It seems this also happens when using `[io.logicblocks/salutem.core "0.1.0"]` instead of the `salutem` reference.
